simulation:

  mode: ODE
  name: Lorenz

  parameters:
    mode: 1
    msf: 1.0

solver:

  run_command: python moving_agents.py --mode $mode --movement_scale_factor $msf --num_runs 100
  replacement_prefix: $
  results_file:  /home/arindam/moving_agents/result.txt
  prefix_commands: ["cd ~/moving_agents", "source .venv/bin/activate"]


simulator:

  parameter_of_interest: msf
  result_dimension: 0
  range: [1, 5]
  n_simulation_points: 5
  sampling_method: latin_hypercube


emulator:

  n_prediction_points: 1000
  n_iterations: 500
  n_layers: 2
  kernel_function: matern2.5
 

plotter:

  directory: plots
  filename: plot_test.png
  x_label: Model Parameter
  y_label: Model Output
