solver:

  run_command: python logistic_lyap.py --r $r

  parameters:
    r: 1.5
  
  replacement_prefix: $
  results_file:  examples/logistic_lyapunov/lyapunov_exponent.txt
  prefix_commands: ["cd examples/logistic_lyapunov"]


simulator:

  parameter_of_interest: r
  result_dimension: 0
  range: [0, 4]
  n_simulation_points: 10
  sampling_method: latin_hypercube


emulator:

  n_prediction_points: 100
  n_iterations: 500
  n_layers: 2
  kernel_function: matern2.5
 

plotter:

  directory: plots
  filename: plot_test.png
  x_label: Model Parameter
  y_label: Model Output
