solver:

  run_command: python moving_agents.py --mode $mode --movement_scale_factor $msf --num_runs 100

  parameters:
    mode: 1
    msf: 1.0
  
  replacement_prefix: $
  results_file:  examples/moving_agents/result.txt
  prefix_commands: ["cd examples/moving_agents"]


simulator:

  parameter_of_interest: msf
  result_dimension: 0
  range: [1, 5]
  n_simulation_points: 5
  sampling_method: latin_hypercube


emulator:

  n_prediction_points: 1000
  n_iterations: 500
  n_layers: 1
  kernel_function: matern2.5
 

plotter:

  directory: plots
  filename: plot_test.png
  x_label: Model Parameter
  y_label: Model Output
