simulation:

  mode: ODE
  name: Lorenz

  parameters:
    sigma: 10
    rho: 28
    beta: 2.667

solver:

  t_range: [0, 100]
  n_steps: 1000
  transience: 0.8

  initial_conditions: [1, 1, 1]


simulator:

  parameter_of_interest: rho
  result_dimension: 0
  range: [2, 20]
  n_simulation_points: 10
  sampling_method: latin_hypercube


emulator:

  n_prediction_points: 1000
  n_iterations: 500
  n_layers: 2
  kernel_function: matern2.5
 

plotter:

  directory: plots
  filename: plot_test.png
  x_label: Model Parameter
  y_label: Model Output
